import Foundation
import CSQLite

// Python owns memory extraction and retrieval. Native deletion invalidates the
// same database immediately, including its FTS trigger, without launching a model.
enum PersonalMemoryStore {
    static func deleteSource(_ id:UUID,replyIDs:[UUID] = [],root:URL)throws {
        let file = root.appendingPathComponent("personal-memory.sqlite")
        guard FileManager.default.fileExists(atPath:file.path) else {return}
        var db:OpaquePointer?
        guard sqlite3_open_v2(file.path,&db,SQLITE_OPEN_READWRITE,nil) == SQLITE_OK else {
            sqlite3_close(db);throw ModelFailure(message:"Could not remove the message from local memory.")
        }
        defer {sqlite3_close(db)}
        sqlite3_busy_timeout(db,1000)
        // UUID is generated by the host, never free-form user or model text.
        let source = id.uuidString
        let hideReplies = replyIDs.map {"INSERT OR IGNORE INTO memory_hidden_messages VALUES ('\($0.uuidString)');"}.joined(separator:"\n")
        let sql = """
        BEGIN IMMEDIATE;
        \(hideReplies)
        INSERT OR IGNORE INTO forgotten_spans(source_id,start,length)
        SELECT s.id,instr(s.body,m.value)-1,length(m.value)
        FROM memory_sources s JOIN memories m ON m.source_id=s.id
        WHERE s.id='\(source)' AND length(m.value)>0 AND instr(s.body,m.value)>0;
        UPDATE memories SET status='deleted',value='',quote='' WHERE source_id='\(source)';
        UPDATE memory_sources SET status='deleted',body='' WHERE id='\(source)';
        COMMIT;
        """
        guard sqlite3_exec(db,sql,nil,nil,nil) == SQLITE_OK else {
            sqlite3_exec(db,"ROLLBACK",nil,nil,nil)
            throw ModelFailure(message:"Could not remove the message from local memory. Please retry deletion.")
        }
    }
}
